"""
EmberWatch Drone Assembly — STL Model Generator
Generates approximate-dimension STL files for the 10 largest components.
All units in mm. Run: python3 generate_models.py
"""

import struct
import math
import os

OUT_DIR = os.path.dirname(os.path.abspath(__file__))


# ---------------------------------------------------------------------------
# STL writer
# ---------------------------------------------------------------------------

def write_stl(filename, triangles):
    path = os.path.join(OUT_DIR, filename)
    with open(path, "wb") as f:
        header = f"Generated by generate_models.py — {filename}".encode()
        f.write(header[:80].ljust(80, b" "))
        f.write(struct.pack("<I", len(triangles)))
        for normal, v1, v2, v3 in triangles:
            for v in (normal, v1, v2, v3):
                f.write(struct.pack("<3f", *v))
            f.write(struct.pack("<H", 0))
    print(f"  Wrote {len(triangles):5d} triangles → {filename}")


# ---------------------------------------------------------------------------
# Primitive builders
# ---------------------------------------------------------------------------

def _normal(v1, v2, v3):
    ax, ay, az = v2[0]-v1[0], v2[1]-v1[1], v2[2]-v1[2]
    bx, by, bz = v3[0]-v1[0], v3[1]-v1[1], v3[2]-v1[2]
    nx = ay*bz - az*by
    ny = az*bx - ax*bz
    nz = ax*by - ay*bx
    L = math.sqrt(nx*nx + ny*ny + nz*nz) or 1.0
    return (nx/L, ny/L, nz/L)


def box(cx, cy, cz, dx, dy, dz):
    """Axis-aligned box centred at (cx,cy,cz) with dimensions dx×dy×dz."""
    x0, x1 = cx - dx/2, cx + dx/2
    y0, y1 = cy - dy/2, cy + dy/2
    z0, z1 = cz - dz/2, cz + dz/2
    quads = [
        ((0, 0,-1), (x0,y0,z0),(x1,y0,z0),(x1,y1,z0),(x0,y1,z0)),
        ((0, 0, 1), (x0,y0,z1),(x0,y1,z1),(x1,y1,z1),(x1,y0,z1)),
        ((0,-1, 0), (x0,y0,z0),(x0,y0,z1),(x1,y0,z1),(x1,y0,z0)),
        ((0, 1, 0), (x0,y1,z0),(x1,y1,z0),(x1,y1,z1),(x0,y1,z1)),
        ((-1,0, 0), (x0,y0,z0),(x0,y1,z0),(x0,y1,z1),(x0,y0,z1)),
        (( 1,0, 0), (x1,y0,z0),(x1,y0,z1),(x1,y1,z1),(x1,y1,z0)),
    ]
    tris = []
    for n, p0, p1, p2, p3 in quads:
        tris.append((n, p0, p1, p2))
        tris.append((n, p0, p2, p3))
    return tris


def cylinder(cx, cy, z0, z1, r, segs=32):
    """Vertical cylinder from z0 to z1, radius r, centred at cx,cy."""
    tris = []
    angles = [2*math.pi*i/segs for i in range(segs)]
    pts_bot = [(cx + r*math.cos(a), cy + r*math.sin(a), z0) for a in angles]
    pts_top = [(cx + r*math.cos(a), cy + r*math.sin(a), z1) for a in angles]
    cb, ct = (cx, cy, z0), (cx, cy, z1)
    for i in range(segs):
        j = (i+1) % segs
        # bottom cap
        n = (0, 0, -1)
        tris.append((n, cb, pts_bot[j], pts_bot[i]))
        # top cap
        n = (0, 0, 1)
        tris.append((n, ct, pts_top[i], pts_top[j]))
        # side
        p0, p1, p2, p3 = pts_bot[i], pts_bot[j], pts_top[j], pts_top[i]
        n = _normal(p0, p1, p2)
        tris.append((n, p0, p1, p2))
        tris.append((n, p0, p2, p3))
    return tris


def tube(cx, cy, z0, z1, r_out, r_in, segs=32):
    """Hollow cylinder (tube) for motor bell detail."""
    tris = []
    angles = [2*math.pi*i/segs for i in range(segs)]
    outer_bot = [(cx + r_out*math.cos(a), cy + r_out*math.sin(a), z0) for a in angles]
    outer_top = [(cx + r_out*math.cos(a), cy + r_out*math.sin(a), z1) for a in angles]
    inner_bot = [(cx + r_in*math.cos(a),  cy + r_in*math.sin(a),  z0) for a in angles]
    inner_top = [(cx + r_in*math.cos(a),  cy + r_in*math.sin(a),  z1) for a in angles]
    for i in range(segs):
        j = (i+1) % segs
        # outer side
        p0,p1,p2,p3 = outer_bot[i],outer_bot[j],outer_top[j],outer_top[i]
        n = _normal(p0,p1,p2)
        tris += [(n,p0,p1,p2),(n,p0,p2,p3)]
        # inner side (reversed winding)
        p0,p1,p2,p3 = inner_bot[i],inner_top[i],inner_top[j],inner_bot[j]
        n = _normal(p0,p1,p2)
        tris += [(n,p0,p1,p2),(n,p0,p2,p3)]
        # bottom ring
        p0,p1,p2,p3 = outer_bot[i],inner_bot[i],inner_bot[j],outer_bot[j]
        n = (0,0,-1)
        tris += [(n,p0,p1,p2),(n,p0,p2,p3)]
        # top ring
        p0,p1,p2,p3 = outer_top[i],outer_top[j],inner_top[j],inner_top[i]
        n = (0,0,1)
        tris += [(n,p0,p1,p2),(n,p0,p2,p3)]
    return tris


def disc(cx, cy, z, r, thickness=1.5, segs=48):
    """Flat disc (propeller plane)."""
    return cylinder(cx, cy, z - thickness/2, z + thickness/2, r, segs)


def arm(cx1, cy1, cx2, cy2, z0, z1, width):
    """Rectangular arm from point 1 to point 2."""
    dx = cx2 - cx1
    dy = cy2 - cy1
    length = math.sqrt(dx*dx + dy*dy)
    angle = math.atan2(dy, dx)
    # perpendicular half-width
    px = -math.sin(angle) * width/2
    py =  math.cos(angle) * width/2
    p = [
        (cx1+px, cy1+py, z0), (cx1-px, cy1-py, z0),
        (cx2-px, cy2-py, z0), (cx2+px, cy2+py, z0),
        (cx1+px, cy1+py, z1), (cx1-px, cy1-py, z1),
        (cx2-px, cy2-py, z1), (cx2+px, cy2+py, z1),
    ]
    tris = []
    faces = [
        ((0,0,-1), 0,1,2,3), ((0,0,1), 4,7,6,5),
        (None,     0,4,5,1), (None,    2,6,7,3),
        (None,     0,3,7,4), (None,    1,5,6,2),
    ]
    for entry in faces:
        if entry[0] is None:
            n_override = None
            i0,i1,i2,i3 = entry[1],entry[2],entry[3],entry[4]
        else:
            n_override, i0,i1,i2,i3 = entry
        q = [p[i0],p[i1],p[i2],p[i3]]
        n = n_override if n_override else _normal(q[0],q[1],q[2])
        tris.append((n,q[0],q[1],q[2]))
        tris.append((n,q[0],q[2],q[3]))
    return tris


# ---------------------------------------------------------------------------
# Component generators
# ---------------------------------------------------------------------------

def gen_frame():
    """
    GEPRC Mark4 7" V2 frame.
    Wheelbase: ~295mm (motor-to-motor), arms at 45°.
    Top/bottom plates: ~170×170mm, 2mm thick, z=0 and z=25mm.
    Arms: 15mm wide, 5mm thick.
    """
    tris = []
    plate_size = 170
    plate_thick = 2.5
    arm_w = 15
    arm_thick = 5
    stack_h = 25  # gap between plates

    # Bottom plate
    tris += box(0, 0, -plate_thick/2, plate_size, plate_size, plate_thick)
    # Top plate
    tris += box(0, 0, stack_h + plate_thick/2, plate_size, plate_size, plate_thick)

    # 4 arms at 45°, motor centres at ~147.5mm from centre
    motor_r = 147.5
    for angle_deg in [45, 135, 225, 315]:
        a = math.radians(angle_deg)
        mx = motor_r * math.cos(a)
        my = motor_r * math.sin(a)
        tris += arm(0, 0, mx, my, 0, arm_thick, arm_w)
        # motor mount pad at tip
        tris += cylinder(mx, my, arm_thick, arm_thick+6, 15, 16)

    return tris


def gen_battery():
    """
    CNHL 1500mAh 6S LiPo — 74×53×35mm (actual spec), 238g.
    """
    tris = []
    # Main body
    tris += box(0, 0, 17.5, 74, 53, 35)
    # Balance plug stub (JST-XH, small protrusion on one end)
    tris += box(37 + 4, 0, 17.5, 8, 12, 8)
    return tris


def gen_jetson():
    """
    Jetson Orin Nano 8GB Devkit carrier board — 100×79mm, ~34mm tall.
    Module sits on top of carrier, adding ~8mm.
    """
    tris = []
    # Carrier board
    tris += box(0, 0, 1.5, 100, 79, 3)
    # Main body / heatsink block
    tris += box(0, 0, 3 + 15, 100, 79, 30)
    # Module protrusion
    tris += box(0, -10, 3 + 30, 70, 45, 8)
    return tris


def gen_motor():
    """
    Xrotor 2807 1300KV — 28mm stator, ~35mm bell dia, ~22mm bell height.
    Visually: flat mounting base + single outer bell (inverted cup) + shaft.
    Stator is hidden inside the bell — not modelled separately.
    """
    tris = []
    # Mounting base plate (~36mm dia, 5mm thick, sits on arm)
    tris += cylinder(0, 0, 0, 5, 18, 32)
    # Outer bell (single inverted cup, 35mm dia, 20mm tall)
    tris += cylinder(0, 0, 5, 25, 17.5, 32)
    # Bell top cap
    tris += disc(0, 0, 25, 17.5, 1.5, 32)
    # Shaft (M5 threaded, 5mm dia, 15mm above bell top)
    tris += cylinder(0, 0, 25, 40, 2.5, 16)
    return tris


def gen_prop():
    """
    HQProp 7.5x3x3 — 190.5mm diameter (7.5" = 190.5mm), tri-blade.
    Blade disc: 2mm thick flat sweep (layout approximation).
    Hub: 18mm OD, 2.5mm shaft hole, 8mm tall.
    """
    tris = []
    # Blade sweep disc (190.5mm dia, 2mm thick)
    tris += disc(0, 0, 0, 190.5/2, 2.0, 48)
    # Hub body (hollow tube: 18mm OD, 5mm shaft hole ID, 8mm tall)
    tris += tube(0, 0, -4, 4, 9, 2.5, 24)
    # Hub top and bottom caps (rings)
    return tris


def gen_esc():
    """
    Tekko32 F4 4-in-1 50A ESC — 40×40mm board, ~8mm thick.
    30.5mm mounting hole pattern.
    """
    tris = []
    tris += box(0, 0, 0, 40, 40, 8)
    # Slightly raised component humps
    tris += box(0, 0, 8, 30, 30, 4)
    return tris


def gen_fc():
    """
    Holybro Kakute H7 v1.5 — 36×36mm board, ~8mm thick.
    30.5mm mounting hole pattern.
    """
    tris = []
    tris += box(0, 0, 0, 36, 36, 7)
    tris += box(0, 0, 7, 28, 28, 5)
    return tris


def gen_gimbal():
    """
    Skydroid C10 Pro — 3-axis gimbal + camera.
    Approx bounding box: 75×55×70mm.
    Camera lens protrudes front.
    """
    tris = []
    # Main gimbal body
    tris += box(0, 0, 35, 55, 40, 70)
    # Camera lens housing (forward)
    tris += cylinder(0, -27, 20, 45, 14, 20)
    # Tilt motor housing (side)
    tris += cylinder(-32, 0, 30, 50, 10, 16)
    tris += cylinder( 32, 0, 30, 50, 10, 16)
    return tris


def gen_camera():
    """
    Waveshare IMX219-160 IR-CUT — PCB 32.04×26.44mm (from datasheet), 3mm thick.
    Two cylindrical IR LED housings protrude from the left and right sides of PCB.
    LED housing: ~9mm dia, ~8mm tall, centre flush with PCB face.
    Total width including LEDs: ~32.04 + 2*(4.5+2) = ~45mm.
    """
    tris = []
    # PCB board
    tris += box(0, 0, 1.5, 32.04, 26.44, 3)
    # Lens barrel (centred on PCB)
    tris += cylinder(0, 0, 3, 14, 6, 20)
    # Lens glass end cap
    tris += disc(0, 0, 14, 6, 1.5, 20)
    # IR LED housings — outside PCB edges (x = ±(16.02 + 2mm gap + 4.5mm radius))
    led_cx = 16.02 + 2 + 4.5   # = 22.52 mm from centre
    tris += cylinder(-led_cx, 0, 0, 8, 4.5, 16)
    tris += cylinder( led_cx, 0, 0, 8, 4.5, 16)
    return tris


def gen_rangefinder():
    """
    TOF400C VL53L1X — PCB ~25×16mm, 3mm thick. Sensor window on top.
    """
    tris = []
    tris += box(0, 0, 1.5, 25, 16, 3)
    # Sensor window (small raised element)
    tris += box(0, 0, 3, 8, 6, 3)
    return tris


# ---------------------------------------------------------------------------
# 3D Printed parts
# ---------------------------------------------------------------------------

def gen_print_landing_leg():
    """
    Tall landing gear leg — L-shaped bracket.
    Vertical post: 14×14mm base, 65mm tall.
    Horizontal foot: 14×40mm, 5mm thick.
    """
    tris = []
    # Vertical post
    tris += box(0, 0, 32.5, 14, 14, 65)
    # Horizontal foot
    tris += box(0, 17, 2.5, 14, 40, 5)
    return tris


def gen_print_jetson_mount():
    """
    Jetson Orin Nano sliding mount — C-hook rail design.
    Jetson (100×79mm, ~3mm PCB) slides in from either side (X direction).
    Front and rear walls each have an inward-facing lip that retains the board.

    Cross-section (looking from X / slide-in direction):
        lip_depth=5mm inward
             ┌────┐         ┌────┐
             │ lip│         │lip │  Z=8–10mm
        ─────┘    │         │    └─────
        front wall│         │rear wall  Z=3–8mm
        ──────────┴─────────┴──────────  base Z=0–3mm
              ←── inner_y = 81mm ───→
    """
    inner_x   = 61    # slide-in direction — reduced by 20mm (was 81mm)
    inner_y   = 102   # front-rear direction — 1mm clearance over 100mm board length
    wall_t    = 3     # front/rear wall thickness
    base_t    = 3     # base plate thickness
    wall_h    = 5     # wall height above base plate
    lip_depth = 5     # lip extends this far inward (overhangs board by ~2mm)
    lip_h     = 2     # lip vertical thickness
    outer_x   = inner_x + 2 * wall_t   # 108mm total width

    tris = []

    # Base plate
    tris += box(0, 0, base_t / 2,
                outer_x, inner_y + 2 * wall_t, base_t)

    # Front wall (+Y)
    fy = inner_y / 2 + wall_t / 2
    tris += box(0,  fy, base_t + wall_h / 2, outer_x, wall_t, wall_h)
    tris += box(0, -fy, base_t + wall_h / 2, outer_x, wall_t, wall_h)

    # Front lip — inward from top of front wall
    lip_cy = inner_y / 2 + wall_t - lip_depth / 2
    tris += box(0,  lip_cy, base_t + wall_h + lip_h / 2, outer_x, lip_depth, lip_h)
    tris += box(0, -lip_cy, base_t + wall_h + lip_h / 2, outer_x, lip_depth, lip_h)

    return tris


def gen_print_gimbal_mount():
    """
    Belly gimbal mount bracket for Skydroid C10 Pro.
    Two vertical side walls + bottom shelf.
    Overall envelope: 80×55×40mm.
    """
    tris = []
    wall_t = 3
    # Left wall
    tris += box(-38.5, 0, 20, wall_t, 55, 40)
    # Right wall
    tris += box(38.5, 0, 20, wall_t, 55, 40)
    # Bottom shelf
    tris += box(0, 0, 1.5, 80, 55, 3)
    # Front lip
    tris += box(0, -26, 8, 80, 3, 16)
    # Rear lip
    tris += box(0, 26, 8, 80, 3, 16)
    return tris


def gen_print_bec_tray():
    """
    BEC tray — simple rectangular tray with low side walls.
    Fits ~50×30mm BEC module.
    """
    tris = []
    wall_t = 2
    floor_t = 2
    inner_w, inner_d = 52, 32
    outer_w = inner_w + 2 * wall_t
    outer_d = inner_d + 2 * wall_t
    height = 10
    # Floor
    tris += box(0, 0, floor_t / 2, outer_w, outer_d, floor_t)
    # Four walls
    tris += box(0,  (inner_d / 2 + wall_t / 2), floor_t + height / 2, outer_w, wall_t, height)
    tris += box(0, -(inner_d / 2 + wall_t / 2), floor_t + height / 2, outer_w, wall_t, height)
    tris += box( (inner_w / 2 + wall_t / 2), 0, floor_t + height / 2, wall_t, inner_d, height)
    tris += box(-(inner_w / 2 + wall_t / 2), 0, floor_t + height / 2, wall_t, inner_d, height)
    return tris


def gen_print_fc_spacer():
    """
    TPU anti-vibration FC spacer — 30.5mm hole pattern, 3mm thick disc.
    Square 8×8mm footprint, 3mm thick, M3 hole (approximated).
    """
    tris = []
    tris += box(0, 0, 1.5, 8, 8, 3)
    return tris


def gen_print_rangefinder_bracket():
    """
    VL53L1X rangefinder bracket.
    L-bracket: horizontal shelf 30×20mm, vertical back wall 30×20mm.
    """
    tris = []
    # Horizontal shelf (holds rangefinder PCB)
    tris += box(0, 5, 1.5, 30, 20, 3)
    # Vertical back wall (mounts to frame)
    tris += box(0, -5, 10, 30, 3, 20)
    return tris


def gen_print_camera_bracket():
    """
    IMX219 belly camera bracket — T-drop design.

    Frame side (top):  flat plate, 2x M3 holes at ±10.95mm (= 21.9mm spacing)
    Camera side (bot): flat plate, 2x M2 holes at ±13.8mm  (= 27.6mm spacing)
    Drop height: 22mm so camera clears belly plate and faces forward-level.

    Side profile:
        ─────────────────────  frame belly plate (reference)
        [  top mount plate  ]  4mm thick, 36×12mm
               │ drop post │   8×8mm, 22mm tall
        [  cam mount plate  ]  4mm thick, 44×30mm
        [   IMX219 PCB      ]  (not part of bracket)

    Top plate bolt centres: y=0, x=±10.95mm
    Bottom plate bolt centres: y=0, x=±13.8mm
    """
    tris = []

    # Top mounting plate (bolts to frame belly, flat top face at z=0)
    tris += box(0, 0, -2, 36, 12, 4)

    # Bolt boss stubs on top plate (M3, visual only — no hole in STL)
    for bx in [10.95, -10.95]:
        tris += cylinder(bx, 0, 0, 3, 3.5, 12)   # small boss, 3mm above plate

    # Vertical drop post (centred, 8×8mm cross-section, 22mm tall)
    tris += box(0, 0, -2 - 11, 8, 8, 22)

    # Bottom camera mount plate (flat bottom face)
    plate_bot_z = -2 - 22  # bottom of drop post
    tris += box(0, 0, plate_bot_z - 2, 44, 30, 4)

    # Camera bolt boss stubs on bottom plate (M2, visual only)
    for bx in [13.8, -13.8]:
        tris += cylinder(bx, 0, plate_bot_z - 4, plate_bot_z - 1, 2.5, 12)

    return tris


def gen_print_cone():
    """
    Traffic cone — 150mm tall, 60mm base radius, ~8mm tip radius.
    """
    tris = []
    h = 150
    r_base = 60
    r_tip = 8
    segs = 32
    base_thick = 8  # flat base disc
    # Conical body (approximated as tube stack or cylinder taper via triangle fan)
    # Build as a tapered cylinder using triangle strips
    angles = [2 * math.pi * i / segs for i in range(segs)]
    # Base ring cap
    cb = (0, 0, base_thick)
    pts_base = [(r_base * math.cos(a), r_base * math.sin(a), base_thick) for a in angles]
    pts_top  = [(r_tip  * math.cos(a), r_tip  * math.sin(a), base_thick + h) for a in angles]
    ct = (0, 0, base_thick + h)
    for i in range(segs):
        j = (i + 1) % segs
        # bottom cap
        tris.append(((0, 0, -1), cb, pts_base[j], pts_base[i]))
        # top cap
        tris.append(((0, 0, 1), ct, pts_top[i], pts_top[j]))
        # side face
        p0, p1, p2, p3 = pts_base[i], pts_base[j], pts_top[j], pts_top[i]
        n = _normal(p0, p1, p2)
        tris.append((n, p0, p1, p2))
        tris.append((n, p0, p2, p3))
    # Flat base disc
    tris += cylinder(0, 0, 0, base_thick, r_base, segs)
    return tris


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

COMPONENTS = [
    ("01_frame_GEPRC_Mark4_7inch.stl",        gen_frame),
    ("02_battery_CNHL_1500mAh_6S.stl",        gen_battery),
    ("03_jetson_orin_nano_devkit.stl",         gen_jetson),
    ("04_motor_Xrotor_2807.stl",              gen_motor),
    ("05_prop_HQProp_7_5x3.stl",              gen_prop),
    ("06_kakute_tekko_stack.stl",            gen_fc),   # merged ESC+FC stack
    ("07_gimbal_Skydroid_C10Pro.stl",         gen_gimbal),
    ("08_camera_IMX219_160.stl",              gen_camera),
    ("09_rangefinder_VL53L1X.stl",            gen_rangefinder),
    # 3D printed parts
    ("print_01_landing_leg.stl",              gen_print_landing_leg),
    ("print_02_jetson_mount.stl",             gen_print_jetson_mount),
    ("print_03_gimbal_mount_bracket.stl",     gen_print_gimbal_mount),
    ("print_04_bec_tray.stl",                 gen_print_bec_tray),
    ("print_05_fc_spacer_tpu.stl",            gen_print_fc_spacer),
    ("print_06_rangefinder_bracket.stl",      gen_print_rangefinder_bracket),
    ("print_07_camera_bracket.stl",           gen_print_camera_bracket),
    ("print_08_traffic_cone.stl",             gen_print_cone),
]

if __name__ == "__main__":
    print(f"Generating models in: {OUT_DIR}\n")
    for fname, gen_fn in COMPONENTS:
        path = os.path.join(OUT_DIR, fname)
        if os.path.exists(path):
            print(f"  SKIP  (already exists) → {fname}")
            continue
        tris = gen_fn()
        write_stl(fname, tris)
    print("\nDone. Use --regen flag to force-regenerate all files.")
    print("Tip: delete a file first if you want to regenerate it.")
